name: aetc-2026
services:
- name: web
  source_dir: /
  github:
    repo: mdYoungDOer/aetc-app
    branch: main
  run_command: npm start
  build_command: npm run build
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 3000
  routes:
  - path: /
  envs:
  - key: NODE_ENV
    value: production
  - key: NEXT_PUBLIC_SUPABASE_URL
    value: ${NEXT_PUBLIC_SUPABASE_URL}
  - key: NEXT_PUBLIC_SUPABASE_ANON_KEY
    value: ${NEXT_PUBLIC_SUPABASE_ANON_KEY}
  - key: SUPABASE_SERVICE_ROLE_KEY
    value: ${SUPABASE_SERVICE_ROLE_KEY}
  - key: SENDGRID_API_KEY
    value: ${SENDGRID_API_KEY}
  - key: SENDGRID_FROM_EMAIL
    value: ${SENDGRID_FROM_EMAIL}
  - key: SENDGRID_FROM_NAME
    value: ${SENDGRID_FROM_NAME}
  - key: PAYSTACK_PUBLIC_KEY
    value: ${PAYSTACK_PUBLIC_KEY}
  - key: PAYSTACK_SECRET_KEY
    value: ${PAYSTACK_SECRET_KEY}
  - key: NEXT_PUBLIC_SITE_URL
    value: ${NEXT_PUBLIC_SITE_URL}
